# .github/workflows/publish.yml
name: Publish auth-core to JitPack

on:
  push:
    tags:
      - ''  # 触发：v1.0.0

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build auth-core
        run: ./gradlew :auth-core:build -x test

      - name: Echo JitPack URL
        run: |
          REPO=$(git remote get-url origin | sed 's/.*github.com\///' | sed 's/\.git$//')
          TAG=${GITHUB_REF#refs/tags/}
          echo "Published: https://jitpack.io/#$REPO/$TAG/auth-core"